apiVersion: apps/v1
kind: Deployment
metadata:
    name: hello-deployment
spec:
    replicas: 3
    selector:
       matchLabels:
          app: hello-docker
    template:
       metadata:
          labels:
             app: hello-docker
       spec:
          containers:
          - name: hello-docker
            image: diiir727/hello-docker:v2.0
            ports:
              - name: web 
                containerPort: 8000
            livenessProbe:
              httpGet:
                port: 8000
                path: /version
              initialDelaySeconds: 10
              periodSeconds: 5
              timeoutSeconds: 2
            readinessProbe:
              httpGet:
                port: 8000
                path: /health
              initialDelaySeconds: 10
              periodSeconds: 5