apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.fullnameOverride }}-config
data:
  GATEWAY_PROFILE_URL: http://profile-service
  GATEWAY_AUTH_URL: http://auth-service
  AUTH_DATABASE_URL: "jdbc:postgresql://postgres-auth:5432/auth"
  PROFILE_DATABASE_URL: "jdbc:postgresql://postgres-profile:5432/profile"



