---
apiVersion: v1
kind: Service
metadata:
  name: postgres-profile
  labels:
    app: postgres-profile
spec:
  type: NodePort
  ports:
   - port: 5432
  selector:
    app: postgres-profile

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-statefulset
spec:
  serviceName: "postgres-profile"
  replicas: 2
  selector:
    matchLabels:
      app: postgres-profile
  template:
    metadata:
      labels:
        app: postgres-profile
    spec:
      containers:
      - name: postgres-profile
        image: postgres:latest
        ports:
        - containerPort: 5432
          name: postgres-profile-db
        env:
          - name: POSTGRES_DB
            value: profile
          - name: POSTGRES_USER
            value: {{ .Values.pgsqlProfile.postgresqlUsername }}
          - name: POSTGRES_PASSWORD
            value: {{ .Values.pgsqlProfile.postgresqlPassword }}
        volumeMounts:
        - name: postgres-profile-db
          mountPath: /var/lib/postgresql-profile/data
          subPath: postgres-profile-db
  volumeClaimTemplates:
  - metadata:
      name: postgres-profile-db
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: standard
      resources:
        requests:
          storage: 1Gi
