apiVersion: v1
kind: Service
metadata:
  name: auth-service
  labels: 
    app.kubernetes.io/name: auth-service
spec:
  type: {{ .Values.authService.type }}
  ports:
    - port: {{ .Values.authService.port }}
      targetPort: {{ .Values.authService.tergetport }}
      protocol: TCP
      name: {{ .Values.authService.name }}
  selector:
    app: auth-app
