apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.fullnameOverride }}-ing
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: {{ .Values.ingress.path }}
            backend:
              serviceName: {{ .Values.fullnameOverride }}-service
              servicePort: 8080
