apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.fullnameOverride }}-initdb
spec:
  template:
    metadata:
      name: {{ .Values.fullnameOverride }}-initdb
    spec:
      restartPolicy: Never
      containers:
      - name: idempotency-install-job
        env:
          - name: DATABASE_URI
            valueFrom:
              secretKeyRef:
                name: {{ .Values.fullnameOverride }}-secret
                key: MIGRATION_URL
        image: postgres:latest
        command:
          - sh
          - "-c"
          - |
            psql $DATABASE_URI <<'EOF'
              create table orders (
                id serial primary key,
                user_id integer not null,
                status integer not null default 0,
                uuid text not null unique,
                order_sum numeric
              );
            EOF
  backoffLimit: 2
