apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.fullnameOverride }}-service
  labels: 
    app.kubernetes.io/name: {{ .Values.fullnameOverride }}-service
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.tergetport }}
      protocol: TCP
      name: {{ .Values.service.name }}
  selector:
    app: {{ .Values.fullnameOverride }}-app
