apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.fullnameOverride }}-secret
type: Opaque
data:
  DB_NAME: {{ .Values.mongodb.mongodbDatabase  | b64enc }}
  DB_USER: {{ .Values.mongodb.mongodbUsername  | b64enc }}
  DB_PASS: {{ .Values.mongodb.mongodbPassword  | b64enc }}