apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo-statefulset
spec:
  serviceName: "mongo"
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - name: mongo
        image: mongo:3.4
        ports:
        - containerPort: 27017
          name: mongodb
        env:
          - name: MONGODB_USERNAME
            valueFrom:
              secretKeyRef:
                name: app-secret
                key: DB_USER
          - name: MONGODB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: app-secret
                key: DB_PASS
          - name: MONGODB_DATABASE
            valueFrom:
              secretKeyRef:
                name: app-secret
                key: DB_NAME
        volumeMounts:
          - name: mongo
            mountPath: /var/lib/mongo/data
            subPath: mongo
  volumeClaimTemplates:
  - metadata:
      name: mongo
    spec:
      accessModes: [ "ReadWrite" ]
      storageClassName: standard
      resources:
        requests:
          storage: 1Gi