apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.fullnameOverride }}-config
data:
  GATEWAY_PROFILE_URL: "http://profile-service"
  GATEWAY_AUTH_URL: "http://auth-service"
  DATABASE_URL: "jdbc:postgresql://postgres-products:5432/myapp"



