apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.fullnameOverride }}-secret
type: Opaque
data:
  DATABASE_USERNAME: {{ .Values.psql.postgresqlUsername  | b64enc  }}
  DATABASE_PASSWORD: {{ .Values.psql.postgresqlPassword  | b64enc  }}
  DATABASE_NAME: {{ .Values.psql.postgresqlDatabase  | b64enc  }}
  MIGRATION_URL: {{ .Values.psql.migrationUrl  | b64enc  }}