apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: myapp-{{ .Values.fullnameOverride }}
  labels:
    app.kubernetes.io/instance: {{ .Values.fullnameOverride }}-monitor
spec:
  jobLabel: myapp-app-chart
  namespaceSelector:
    matchNames:
    - {{ .Values.metrics.namespace }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.fullnameOverride }}-service
  endpoints:
  - interval: 15s
    port: {{ .Values.service.name }}
    path: {{ .Values.metrics.path }}
