{
 "title": "User get rpc2",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Nginx errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status) (rate(nginx_ingress_controller_request_duration_seconds_count{status=\"500\"}[1m]))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "App errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(create_user_seconds_count{status=\"500\"}[1m]))",
     "legendFormat": "create user 500"
    },
    {
     "expr": "sum(rate(get_user_seconds_count{status=\"500\"}[1m]))",
     "legendFormat": "get user 500"
    },
    {
     "expr": "sum(rate(delete_user_seconds_count{status=\"500\"}[1m]))",
     "legendFormat": "delete user 500"
    },
    {
     "expr": "sum(rate(update_user_seconds_count{status=\"500\"}[1m]))",
     "legendFormat": "update user 500"
    }
   ]
  },
  {
   "title": "NGINX RPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (method) (rate (nginx_ingress_controller_request_duration_seconds_count[1m]))"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(get_user_seconds_count[1m]))",
     "legendFormat": "get user"
    },
    {
     "expr": "sum(rate(delete_user_seconds_count[1m]))",
     "legendFormat": "delete user"
    },
    {
     "expr": "sum(rate(update_user_seconds_count[1m]))",
     "legendFormat": "update user"
    },
    {
     "expr": "sum(rate(create_user_seconds_count[1m]))",
     "legendFormat": "create user"
    },
    {}
   ]
  },
  {
   "title": "NGINX Quantiles",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum (rate(nginx_ingress_controller_response_duration_seconds_bucket[2m])) by (le, method))"
    }
   ]
  },
  {
   "title": "Quantiles",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (quantile) (get_user_seconds{quantile=~\"0.5|0.95|0.99\"})",
     "legendFormat": "get user {{quantile}}"
    },
    {
     "expr": "sum by (quantile) (create_user_seconds{quantile=~\"0.5|0.95|0.99\"})",
     "legendFormat": "create user {{quantile}}"
    },
    {
     "expr": "sum by (quantile) (delete_user_seconds{quantile=~\"0.5|0.95|0.99\"})",
     "legendFormat": "delete user {{quantile}}"
    },
    {
     "expr": "sum by (quantile) (update_user_seconds{quantile=~\"0.5|0.95|0.99\"})",
     "legendFormat": "update user {{quantile}}"
    }
   ]
  },
  {
   "title": "Max latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "max(get_user_seconds_max)", "legendFormat": "get user" },
    { "expr": "max(create_user_seconds_max)", "legendFormat": "create user" },
    { "expr": "max(delete_user_seconds_max)", "legendFormat": "delete user" },
    { "expr": "max(update_user_seconds_max)", "legendFormat": "update user" }
   ]
  }
 ]
}